// lib/skillDocs.js
// Map each skill label to doc URL + level (0..1).
export const DOCS = {
  "JavaScript": "https://developer.mozilla.org/docs/Web/JavaScript",
  "C": "https://en.cppreference.com/w/c",
  "Redis": "https://redis.io/docs/latest/",
  "MongoDB": "https://www.mongodb.com/docs/",
  "SQL": "https://www.postgresql.org/docs/",
  "CSS": "https://developer.mozilla.org/docs/Web/CSS",
  "Markdown": "https://www.markdownguide.org/basic-syntax/",
  "HTML": "https://developer.mozilla.org/docs/Web/HTML",
  "Python": "https://docs.python.org/3/",
  "React": "https://react.dev/learn",
  "PostgreSQL": "https://www.postgresql.org/docs/",
  "Rust": "https://doc.rust-lang.org/book/",
  "Vanilla JS": "https://developer.mozilla.org/docs/Web/JavaScript",
  "Vue.js": "https://vuejs.org/guide/introduction.html",
  "Angular": "https://angular.dev/overview",
  "Windows": "https://learn.microsoft.com/windows/",
  "Linux": "https://www.kernel.org/doc/html/latest/",
  "macOS": "https://support.apple.com/guide/mac-help/welcome/mac",
  "Debian": "https://www.debian.org/doc/",
  "Git": "https://git-scm.com/docs",
  "GitHub": "https://docs.github.com",
  "VS Code": "https://code.visualstudio.com/docs",
  "WebStorm": "https://www.jetbrains.com/help/webstorm/",
  "Microsoft Office": "https://support.microsoft.com/office",
  "Excel": "https://support.microsoft.com/excel",
};

export const LEVELS_0_TO_1 = {
  "JavaScript": 0.9,
  "C": 0.7,
  "Redis": 0.6,
  "MongoDB": 0.8,
  "SQL": 0.7,
  "CSS": 0.7,
  "Markdown": 0.8,
  "HTML": 0.8,
  "Python": 0.7,
  "React": 0.7,
  "PostgreSQL": 0.6,
  "Rust": 0.4,
  "Vanilla JS": 0.7,
  "Vue.js": 0.5,
  "Angular": 0.5,
  "Windows": 0.8,
  "Linux": 0.7,
  "macOS": 0.8,
  "Debian": 0.6,
  "Git": 0.8,
  "GitHub": 0.8,
  "VS Code": 0.8,
  "WebStorm": 0.6,
  "Microsoft Office": 0.8,
  "Excel": 0.7,
};
